/* Generated By:JavaCC: Do not edit this line. KRSSParserConstants.java */
package org.coode.owl.krssparser;

public interface KRSSParserConstants {

  int EOF = 0;
  int URI_START = 5;
  int URI_END = 6;
  int STRING_LITERAL_START = 8;
  int STRINGLITERAL = 10;
  int OPENPAR = 12;
  int CLOSEPAR = 13;
  int ENDTBOX = 14;
  int ENDABOX = 15;
  int PRIMITIVECONCEPT = 16;
  int DEFINEPRIMITIVECONCEPT = 17;
  int DEFINECONCEPT = 18;
  int DEFINEPRIMITIVEROLE = 19;
  int SUBROLE = 20;
  int TRANSITIVE = 21;
  int ENUM = 22;
  int RANGE = 23;
  int AND = 24;
  int OR = 25;
  int NOT = 26;
  int ALL = 27;
  int SOME = 28;
  int NONE = 29;
  int ATLEAST = 30;
  int ATMOST = 31;
  int EXACTLY = 32;
  int INSTANCE = 33;
  int RELATED = 34;
  int EQUAL = 35;
  int DISTINCT = 36;
  int NAME = 37;
  int INT = 38;

  int DEFAULT = 0;
  int IN_URI = 1;
  int IN_STRING_LITERAL = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"<\"",
    "\">\"",
    "<token of kind 7>",
    "\"\\\"\"",
    "\"\\\\\\\"\"",
    "\"\\\"\"",
    "<token of kind 11>",
    "\"(\"",
    "\")\"",
    "\"end-tbox\"",
    "\"end-abox\"",
    "\"primitive-concept\"",
    "\"define-primitive-concept\"",
    "\"define-concept\"",
    "\"define-primitive-role\"",
    "\"subrole\"",
    "\"transitive\"",
    "\"enum\"",
    "\"range\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"all\"",
    "\"some\"",
    "\"none\"",
    "\"at-least\"",
    "\"at-most\"",
    "\"exactly\"",
    "\"instance\"",
    "\"related\"",
    "\"equal\"",
    "\"distinct\"",
    "<NAME>",
    "<INT>",
    "\":right-identity\"",
  };

}
