/* Generated By:JavaCC: Do not edit this line. DLSyntaxParserConstants.java */
package uk.ac.manchester.cs.owl.dlsyntax.parser;

public interface DLSyntaxParserConstants {

  int EOF = 0;
  int SUBCLASSOF = 4;
  int EQUIVALENTTO = 5;
  int DOT = 6;
  int INVERSE = 7;
  int OPENPAR = 8;
  int CLOSEPAR = 9;
  int OPENSQPAR = 10;
  int CLOSESQPAR = 11;
  int OPENBRACE = 12;
  int CLOSEBRACE = 13;
  int COLON = 14;
  int AND = 15;
  int OR = 16;
  int NOT = 17;
  int SOME = 18;
  int ALL = 19;
  int MIN = 20;
  int MAX = 21;
  int EXACT = 22;
  int IN = 23;
  int TRANSITIVEROLES = 24;
  int INT = 25;
  int ID = 26;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<SUBCLASSOF>",
    "<EQUIVALENTTO>",
    "\".\"",
    "<INVERSE>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<SOME>",
    "<ALL>",
    "<MIN>",
    "<MAX>",
    "<EXACT>",
    "<IN>",
    "<TRANSITIVEROLES>",
    "<INT>",
    "<ID>",
    "\"\\n\"",
  };

}
